# autogenerated by txs
#include:fontenc
#include:ifpdf
\csname#S
\filedate#S
\fileversion#S
\pdfstringdefPreHook#S
CJK.sty#S
\__file_name=CJK.sty#S
\__file_name=fontenc.sty#S
\__file_name=ifpdf.sty#S
\__file_name=inputenc.sty#S
\__hook CJK#S
\__hook fontenc#S
\__hook ifpdf#S
\__hook inputenc#S
\unprocessedoptions-CJK.sty#S
\unprocessedoptions-fontenc.sty#S
\unprocessedoptions-ifpdf.sty#S
\unprocessedoptions-inputenc.sty#S
csnameendcsname#S
fontenc.sty#S
ifpdf.sty#S
inputenc.sty#S
