# autogenerated by txs
#include:afterpage
#include:everypage
#include:tikz
#include:xkeyval
\BgMaterial#S
\BgThispage#S
\NoBgThispage#S
\SetBgAnchor{arg1}#S
\SetBgAngle{arg1}#S
\SetBgColor{arg1}#S
\SetBgContents{arg1}#S
\SetBgHshift{arg1}#S
\SetBgOpacity{arg1}#S
\SetBgPosition{arg1}#S
\SetBgScale{arg1}#S
\SetBgVshift{arg1}#S
\backgroundsetup{arg1}#S
\bg#S
\backgroundsetup #S
afterpage.sty#S
everypage.sty#S
tikz.sty#S
xkeyval.sty#S
